spring:
    servlet:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB
    http:
        multipart:
            enabled: false
java:
    util:
        logging:
            config:
                file:
                    value: "WEB-INF/classes/logging.properties"
management:
    endpoints:
        web:
            cors:
                allowed-origins: http://localhost:4200

---
spring:
    profiles: prod

management:
    endpoints:
        web:
            cors:
                allowed-origins: http://storage.googleapis.com/hat-web-01
