dialect  "java"

rule "Hair color is Black"
       salience 100
    when
        $pledge: sortinghat.Student (getHairColor().equalsIgnoreCase("black"));
    then
        $pledge.setHouse("Gryffindor");
        retract( $pledge );
end

rule "Hair Color is Silver"
       salience 100
    when
        $pledge: sortinghat.Student (getHairColor().equalsIgnoreCase("silver"));
    then
        $pledge.setHouse("Slytherin");
        retract( $pledge );
end

rule "Super Rich"
       salience 90
    when
        $pledge: sortinghat.Student (getNetWorth() > 10000000)
    then
        $pledge.setHouse("Slytherin");
        retract( $pledge );
end

rule "Not Brave"
       salience 80
    when
        $pledge: sortinghat.Student (getDementorsBattled() == 0)
    then
        $pledge.setHouse("Slytherin");
        retract( $pledge );
end

rule "Brave"
       salience 80
    when
        $pledge: sortinghat.Student (getDementorsBattled() > 0)
    then
end


rule "Mean"
       salience 70
    when
        $pledge: sortinghat.Student (getElvesOwned() > 0)
    then
        $pledge.setHouse("Slytherin");
        retract( $pledge );
end

rule "Nice"
       salience 70
    when
        $pledge: sortinghat.Student (getElvesOwned() == 0)
    then
end

rule "Random Group 1"
       salience 30
    when
        $pledge: sortinghat.Student (getRandomGroup() == 0)
    then
        $pledge.setHouse("Gryffindor");
        retract( $pledge );

end

rule "Random Group 2"
       salience 30
    when
        $pledge: sortinghat.Student (getRandomGroup() == 1)
    then
        $pledge.setHouse("Ravenclaw");
        retract( $pledge );
end

rule "Random Group 3"
       salience 30
    when
        $pledge: sortinghat.Student (getRandomGroup() == 2)
    then
        $pledge.setHouse("Hufflepuff");
        retract( $pledge );
end
